export enum RootScreens {
  MAIN = "Main",
  WELCOME = "Welcome",
  SPLASH = "SplashScreen",
  LOGIN = "Login",
  MAINTREE = "MainTree",
  PROFILE = "Profile",
  UPDATEPROFILE = "UpdateProfile",
  NOTIFY = "Notify",
  STATISTIC = "Statistic",
  HOME = "Home",
  ADDFARM= "Add Farm",
  REGISTER1 = "Register1",
  REGISTER2 = "Register2",
  REGISTER3 = "Register3",
  REGISTER4 = "Register4",
}
